//**********************************************************************`
//* This is an include file generated by Message Compiler.             *`
//*                                                                    *`
//* Copyright (c) Microsoft Corporation. All Rights Reserved.          *`
//**********************************************************************`
#pragma once
//+
// Provider Maximodex-ETW-MxUtils1 Event Count 2
//+
EXTERN_C __declspec(selectany) const GUID MxUtils1Lib_Events = {0x86563644, 0x640d, 0x417e, {0xab, 0x6f, 0x0f, 0x54, 0x3b, 0x04, 0x28, 0xd9}};

//
// Opcodes
//
#define MxSetError 0xa
#define MxLogMsg 0xb

//
// Tasks
//
#define MxEventTask 0x1
//
// Keyword
//
#define MxErrorEventKW 0x800000000000
#define MxLogEventKW 0x400000000000

//
// Event Descriptors
//
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR MxErrorEvent = {0x1, 0x1, 0x0, 0x2, 0xa, 0x1, 0x800000000000};
#define MxErrorEvent_value 0x1
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR MxLogEvent = {0x2, 0x1, 0x0, 0x4, 0xb, 0x1, 0x400000000000};
#define MxLogEvent_value 0x2
#define MSG_Maximodex_ETW_MxUtils1_Keyword_MxLogEventKW_message 0x1000002FL
#define MSG_Maximodex_ETW_MxUtils1_Keyword_MxErrorEventKW_message 0x10000030L
#define MSG_Maximodex_ETW_MxUtils1_opcode_MxSetError_message 0x3000000AL
#define MSG_Maximodex_ETW_MxUtils1_opcode_MxLogMsg_message 0x3000000BL
#define MSG_level_Error                      0x50000002L
#define MSG_level_Informational              0x50000004L
#define MSG_Maximodex_ETW_MxUtils1_task_MxEventTask_message 0x70000001L
#define MSG_Maximodex_ETW_MxUtils1_event_1_message 0xB0010001L
#define MSG_Maximodex_ETW_MxUtils1_event_2_message 0xB0010002L
