#pragma once
//=====================================================================================================================================================
//IPluginStdLib.h - Sample implementaton of IMxPluginLibDetails - DO NOT EDIT THIS FILE
//=====================================================================================================================================================

#include "IMxPluginLibDetails.h"

static const GUID IPluginStdLibGUID = { 0xc4706f5a, 0x5305, 0x4be2, { 0xaa, 0x89, 0x97, 0x3c, 0xe1, 0xd0, 0xe8, 0xdc } };		// {C4706F5A-5305-4BE2-AA89-973CE1D0E8DC}
class IPluginStdLibIID
{
public:
	static const GUID		  Guid() { return IPluginStdLibGUID; }
	static const char * const Name() { return "IPluginStdLib"; }
};


class  IPluginStdLib : public IMxPluginLibDetails 
{
public:
	virtual const char *MXSTDMETHOD GetComment(void) = 0;	

};


