#pragma once
//=====================================================================================================================================================
//IPluginStdInterface.h - Prototype implementation of IMxPluginBase interface - DO NOT EDIT THIS FILE
//=====================================================================================================================================================

#include "..\IMxPluginBase.h"

static const GUID IPluginStdInterfaceLibGUID = { 0x3a8882ca, 0xcdec, 0x49e4, { 0x9c, 0xb0, 0x77, 0x1d, 0xb3, 0x3, 0x77, 0x9a } };  // {3A8882CA-CDEC-49E4-9CB0-771DB303779A}
class IPluginStdInterfaceLibIID
{
public:
	static const GUID		  Guid() { return IPluginStdInterfaceLibGUID; }
	static const char * const Name() { return "IMxPluginBase"; }
};

class IPluginStdInterfaceLib : public IMxPluginBase
{
public:
virtual const char *MXSTDMETHOD	GetComment() = 0; 

};

